import "server-only";

import { parseServerEnvironment, type ServerEnvironment } from "./schema";

export function getServerEnvironment(input?: unknown): ServerEnvironment {
  return parseServerEnvironment(
    input ?? {
      NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
      NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
      NEXT_PUBLIC_TURNSTILE_SITE_KEY: process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY,
      HUDDLE_ENVIRONMENT: process.env.HUDDLE_ENVIRONMENT,
      SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
      FOOTBALL_DATA_API_TOKEN: process.env.FOOTBALL_DATA_API_TOKEN,
      SPORTS_SYNC_SECRET: process.env.SPORTS_SYNC_SECRET,
      DISCOVERY_CURSOR_SECRET: process.env.DISCOVERY_CURSOR_SECRET,
      AUTH_RECOVERY_TOKEN_SECRET: process.env.AUTH_RECOVERY_TOKEN_SECRET,
      AUTH_TURNSTILE_ENABLED: process.env.AUTH_TURNSTILE_ENABLED,
      TURNSTILE_SECRET: process.env.TURNSTILE_SECRET,
      TURNSTILE_HOSTNAMES: process.env.TURNSTILE_HOSTNAMES,
      ASSISTED_DISCOVERY_ENABLED: process.env.ASSISTED_DISCOVERY_ENABLED,
      ASSISTED_DISCOVERY_TOKEN_SECRET: process.env.ASSISTED_DISCOVERY_TOKEN_SECRET,
      CLOUDFLARE_ACCOUNT_ID: process.env.CLOUDFLARE_ACCOUNT_ID,
      CLOUDFLARE_WORKERS_AI_API_TOKEN: process.env.CLOUDFLARE_WORKERS_AI_API_TOKEN,
      VERCEL_ENV: process.env.VERCEL_ENV,
    },
  );
}
